export const REPOS_LIST_REFRESH = 'REPOS_LIST_REFRESH'
export const REPOS_LIST_LOADMORE = 'REPOS_LIST_LOADMORE'

export const STARRED_REPO_REFRESH = 'STARRED_REPO_REFRESH'
export const STARRED_REPO_LOADMORE = 'STARRED_REPO_LOADMORE'

export const REPO_INFO = 'REPO_INFO'
export const REPO_README = 'REPO_README'
